language: elixir
elixir:
  - 1.4.5

addons:
postgresql: '9.6.1'

services:
  - postgresql

before_script:
- cp config/travis.exs config/test.exs
- mix do ecto.create, ecto.migrate

script:
  - mix tes
